module.exports = {
    ELEMENT_TIMEOUT: 10,
    PAGE_LOAD_TIMEOUT: 30,
    runBusinessTest: false, //  Set to "true" to run test for Business products
    runPersonalTest: true, //  Set to "true" to run test for Personal products
  
    cards: {
      personal: ["Cash Rewards World Visa", "Platinum Visa", "Secured Visa"],
      business: [
        "Commercial Rewards VISA",
        "Small Business Rewards VISA",
        "Small Business Platinum VISA",
      ],
    },
  
    //Common variables that will be used for all products
    commonVariables: [
      {
        peopleID: "U.S. State Issued Identification",
        peoplePhoneType: "Home",
        peopleAccountType: "Checking",
        countryofCitizenship: "United States",
        addressDurationYears: "2",
        addressDurationMonths: "2",
        emailAddress: "test@mkdecision.com",
        housingType: "Rent",
        monthlyPayment: "1200",
        occupation: "Sales",
        employmentStatus: "Full-time",
        employerName: "Target",
        employmentTitle: "Cashier",
        employmentDurationYears: "2",
        employmentDurationMonths: "3",
        employmentAddress1: "123 West Way",
        employmentPostalCode: "77086",
        transferBalancePostalCode: "92618",
        bankRoutingNum: "091000019",
        transferInstitution: "Partner's Credit Union",
        accountNumber: "123456789",
        relationToApp: "Friend",
        coAppIdNum: "1234ABCD",
        coAppStateIssue: "Texas",
        coAppIssueDate: "12222019",
        coAppExDate: "12222222",
        principal1AnnualIncome: "10000",
        principal1YAO: "2",
      },
    ],
    people: [
      {
        creditResponsible: "JOINT",
        personalAmountCreditRequested: "1000",
        firstName: "CATHY",
        middleInitial: "",
        lastName: "BOUNDS",
        suffix: "",
        birthDate: "03261950",
        socialSecurityNumber: "666720873",
        address1: "37 SHORE DR",
        FIELD12: "VERON",
        FIELD13: "NJ",
        postalCode: "07462",
        addressYears: "2",
        addressMonths: "3",
        mailingAddress: "",
        FIELD16: "",
        FIELD17: "",
        mailingPostalCode: "",
        primaryPhoneNumber: "9738235418",
        monthlyIncome: "$6,713.00",
        kba: "",
        co_firstName: "GERRI",
        co_middleInitial: "L",
        co_lastName: "HAMPTON",
        co_suffix: "",
        co_birthDate: "06161955",
        co_socialSecurityNumber: "666380622",
        co_address1: "335 S MADISON ST",
        FIELD29: "LANCASTER",
        FIELD30: "WI",
        co_postalCode: "53813",
        co_primaryPhoneNumber: "6087236418",
        co_monthlyIncome: "$5,769.00",
        co_mailingAddress: "",
        FIELD35: "",
        FIELD36: "",
        co_mailingPostalCode: "",
        auth_firstName: "",
        auth_middleInitial: "",
        auth_lastName: "",
        auth_suffix: "",
        auth_birthDate: "",
        auth_socialSecurityNumber: "",
        institutionName: "",
        bt_Amount: "",
        bt_Name: "",
        bt_MailingAdress: "",
        bt_PostalCode: "",
        institutionName2: "",
        bt_Amount2: "",
        bt_Name2: "",
        bt_MailingAdress2: "",
        bt_PostalCode2: "",
      },
      {
        creditResponsible: "JOINT",
        personalAmountCreditRequested: "1000",
        FIELD4: "",
        firstName: "JOHNNIE",
        middleInitial: "",
        lastName: "BAY",
        suffix: "",
        birthDate: "07291959",
        socialSecurityNumber: "666669201",
        address1: "4621 TULIP TREE CT",
        FIELD12: "CHANTILLY",
        FIELD13: "VA",
        postalCode: "20151",
        mailingAddress: "",
        FIELD16: "",
        FIELD17: "",
        mailingPostalCode: "",
        primaryPhoneNumber: "9148367412",
        monthlyIncome: "$15,000.00",
        kba: "1",
        co_firstName: "DARLENE",
        co_middleInitial: "",
        co_lastName: "HILLARD",
        co_suffix: "",
        co_birthDate: "06051973",
        co_socialSecurityNumber: "666126324",
        co_address1: "53 PARK PL",
        FIELD29: "NEW YORK",
        FIELD30: "NY",
        co_postalCode: "100072",
        co_primaryPhoneNumber: "3378562076",
        co_monthlyIncome: "$3,712.00",
        co_mailingAddress: "PO BOX 89",
        FIELD35: "NEW YORK",
        FIELD36: "NY",
        co_mailingPostalCode: "10007",
        auth_firstName: "",
        auth_middleInitial: "",
        auth_lastName: "",
        auth_suffix: "",
        auth_birthDate: "",
        auth_socialSecurityNumber: "",
        institutionName: "",
        bt_Amount: "",
        bt_Name: "",
        bt_MailingAdress: "",
        bt_PostalCode: "",
        institutionName2: "",
        bt_Amount2: "",
        bt_Name2: "",
        bt_MailingAdress2: "",
        bt_PostalCode2: "",
      },
      {
        creditResponsible: "JOINT",
        personalAmountCreditRequested: "1000",
  
        productName: "Rewards Platinum Visa®",
        FIELD4: "",
        firstName: "JASON",
        middleInitial: "D",
        lastName: "JASMES HARRISON",
        suffix: "",
        birthDate: "04011956",
        socialSecurityNumber: "666449598",
        address1: "1544 STONE VALLEY AVE",
        FIELD12: "LAS VEGAS",
        FIELD13: "NV",
        postalCode: "89123",
        mailingAddress: "",
        FIELD16: "",
        FIELD17: "",
        mailingPostalCode: "",
        primaryPhoneNumber: "7024544611",
        monthlyIncome: "$3,745.00",
        kba: "",
        co_firstName: "ANGELA",
        co_middleInitial: "",
        co_lastName: "PASILLAS",
        co_suffix: "",
        co_birthDate: "10061953",
        co_socialSecurityNumber: "666393333",
        co_address1: "249 CEDAR CRK",
        FIELD29: "SULPHUR SPRINGS",
        FIELD30: "TX",
        co_postalCode: "75482",
        co_primaryPhoneNumber: "9034395923",
        co_monthlyIncome: "$3,710.00",
        co_mailingAddress: "",
        FIELD35: "",
        FIELD36: "",
        co_mailingPostalCode: "",
        auth_firstName: "",
        auth_middleInitial: "",
        auth_lastName: "",
        auth_suffix: "",
        auth_birthDate: "",
        auth_socialSecurityNumber: "",
        institutionName: "",
        bt_Amount: "",
        bt_Name: "",
        bt_MailingAdress: "",
        bt_PostalCode: "",
        institutionName2: "",
        bt_Amount2: "",
        bt_Name2: "",
        bt_MailingAdress2: "",
        bt_PostalCode2: "",
      },
      {
        creditResponsible: "JOINT",
        personalAmountCreditRequested: "1000",
        productName: "Rewards Platinum Visa®",
        FIELD4: "",
        firstName: "JANET",
        middleInitial: "",
        lastName: "THOMAS",
        suffix: "",
        birthDate: "04011950",
        socialSecurityNumber: "666084249",
        address1: "312 MAIN ST",
        FIELD12: "HOT SPRINGS NATIONAL",
        FIELD13: "AR",
        postalCode: "71913",
        mailingAddress: "",
        FIELD16: "",
        FIELD17: "",
        mailingPostalCode: "",
        primaryPhoneNumber: "5013185258",
        monthlyIncome: "$2,500.00",
        kba: "",
        co_firstName: "GRISELDA",
        co_middleInitial: "C",
        co_lastName: "BOND",
        co_suffix: "",
        co_birthDate: "02071953",
        co_socialSecurityNumber: "666254028",
        co_address1: "332 YORKTOWN DR",
        FIELD29: "FORKED RIVER",
        FIELD30: "NJ",
        co_postalCode: "08731",
        co_primaryPhoneNumber: "9565462169",
        co_monthlyIncome: "$6,396.00",
        co_mailingAddress: "1847 ALDEN AVE",
        FIELD35: "SHAKOPEE",
        FIELD36: "MN",
        co_mailingPostalCode: "55379",
        auth_firstName: "",
        auth_middleInitial: "",
        auth_lastName: "",
        auth_suffix: "",
        auth_birthDate: "",
        auth_socialSecurityNumber: "",
        institutionName: "",
        bt_Amount: "",
        bt_Name: "",
        bt_MailingAdress: "",
        bt_PostalCode: "",
        institutionName2: "",
        bt_Amount2: "",
        bt_Name2: "",
        bt_MailingAdress2: "",
        bt_PostalCode2: "",
      },
      {
        creditResponsible: "JOINT",
        personalAmountCreditRequested: "1000",
        productName: "Rewards Platinum Visa®",
        FIELD4: "",
        firstName: "MARJORIE",
        middleInitial: "C",
        lastName: "FUNDYGA",
        suffix: "",
        birthDate: "08101952",
        socialSecurityNumber: "666701547",
        address1: "3 GLORIA LN",
        FIELD12: "NORTH READING",
        FIELD13: "MA",
        postalCode: "01864",
        mailingAddress: "PO BOX 2807",
        FIELD16: "DECATUR",
        FIELD17: "AL",
        mailingPostalCode: "35602",
        primaryPhoneNumber: "4809628863",
        monthlyIncome: "$2,236.00",
        kba: "",
        co_firstName: "JULIA",
        co_middleInitial: "",
        co_lastName: "ORGANIC",
        co_suffix: "",
        co_birthDate: "06271945",
        co_socialSecurityNumber: "666713547",
        co_address1: "760 MIDSTREAMS RD",
        FIELD29: "BRICK ",
        FIELD30: "NJ",
        co_postalCode: "08724",
        co_primaryPhoneNumber: "2523364429",
        co_monthlyIncome: "$1,500.00",
        co_mailingAddress: "",
        FIELD35: "",
        FIELD36: "",
        co_mailingPostalCode: "",
        auth_firstName: "",
        auth_middleInitial: "",
        auth_lastName: "",
        auth_suffix: "",
        auth_birthDate: "",
        auth_socialSecurityNumber: "",
        institutionName: "",
        bt_Amount: "",
        bt_Name: "",
        bt_MailingAdress: "",
        bt_PostalCode: "",
        institutionName2: "",
        bt_Amount2: "",
        bt_Name2: "",
        bt_MailingAdress2: "",
        bt_PostalCode2: "",
      },
      {
        creditResponsible: "JOINT",
        personalAmountCreditRequested: "1000",
  
        productName: "Cash Rewards Platinum Visa®",
        FIELD4: "",
        firstName: "MARK",
        middleInitial: "",
        lastName: "CASTOR",
        suffix: "",
        birthDate: "03251927",
        socialSecurityNumber: "666195945",
        address1: "27 ALAMO DR",
        FIELD12: "BUFFALO",
        FIELD13: "MO",
        postalCode: "65622",
        mailingAddress: "",
        FIELD16: "",
        FIELD17: "",
        mailingPostalCode: "",
        primaryPhoneNumber: "4173452659",
        monthlyIncome: "$1,500.00",
        kba: "",
        co_firstName: "BRUCE",
        co_middleInitial: "",
        co_lastName: "AVERELL",
        co_suffix: "",
        co_birthDate: "02281938",
        co_socialSecurityNumber: "666062187",
        co_address1: "14 ALPINE DR",
        FIELD29: "CARTERSVILLE",
        FIELD30: "GA",
        co_postalCode: "30120",
        co_primaryPhoneNumber: "2523364429",
        co_monthlyIncome: "$3,667.00",
        co_mailingAddress: "",
        FIELD35: "",
        FIELD36: "",
        co_mailingPostalCode: "",
        auth_firstName: "",
        auth_middleInitial: "",
        auth_lastName: "",
        auth_suffix: "",
        auth_birthDate: "",
        auth_socialSecurityNumber: "",
        institutionName: "",
        bt_Amount: "",
        bt_Name: "",
        bt_MailingAdress: "",
        bt_PostalCode: "",
        institutionName2: "",
        bt_Amount2: "",
        bt_Name2: "",
        bt_MailingAdress2: "",
        bt_PostalCode2: "",
      },
      {
        creditResponsible: "JOINT",
        personalAmountCreditRequested: "1000",
        productName: "Visa® Signature Travel",
        FIELD4: "",
        firstName: "JANINE",
        middleInitial: "B",
        lastName: "BUTLER",
        suffix: "",
        birthDate: "02181958",
        socialSecurityNumber: "666068544",
        address1: "921 CRESCENT LN",
        FIELD12: "BISMARCK",
        FIELD13: "ND",
        postalCode: "58501",
        mailingAddress: "",
        FIELD16: "",
        FIELD17: "",
        mailingPostalCode: "",
        primaryPhoneNumber: "7012584599",
        monthlyIncome: "$15,000.00",
        kba: "",
        co_firstName: "RETA",
        co_middleInitial: "F",
        co_lastName: "SAMBROT",
        co_suffix: "",
        co_birthDate: "07081939",
        co_socialSecurityNumber: "666391488",
        co_address1: "8404 MONTANA AVE",
        FIELD29: "BROWNSVILLE",
        FIELD30: "TX",
        co_postalCode: "78526",
        co_primaryPhoneNumber: "3072377475",
        co_monthlyIncome: "$3,000.00",
        co_mailingAddress: "",
        FIELD35: "",
        FIELD36: "",
        co_mailingPostalCode: "",
        auth_firstName: "",
        auth_middleInitial: "",
        auth_lastName: "",
        auth_suffix: "",
        auth_birthDate: "",
        auth_socialSecurityNumber: "",
        institutionName: "",
        bt_Amount: "",
        bt_Name: "",
        bt_MailingAdress: "",
        bt_PostalCode: "",
        institutionName2: "",
        bt_Amount2: "",
        bt_Name2: "",
        bt_MailingAdress2: "",
        bt_PostalCode2: "",
      },
      {
        creditResponsible: "JOINT",
        personalAmountCreditRequested: "1000",
        productName: "Rewards Platinum Visa®",
        FIELD4: "",
        firstName: "ONNIE",
        middleInitial: "",
        lastName: "SCHMIDT JACKSON",
        suffix: "",
        birthDate: "05011928",
        socialSecurityNumber: "666602133",
        address1: "44 NORTH ST",
        FIELD12: "ASHEVILLE",
        FIELD13: "NC",
        postalCode: "28801",
        mailingAddress: "",
        FIELD16: "",
        FIELD17: "",
        mailingPostalCode: "",
        primaryPhoneNumber: "8282515682",
        monthlyIncome: "$5,769.00",
        kba: "",
        co_firstName: "BENJAMIN",
        co_middleInitial: "W",
        co_lastName: "EXON",
        co_suffix: "SR",
        co_birthDate: "08221963",
        co_socialSecurityNumber: "666429330",
        co_address1: "4351 STATE ROUTE 314",
        FIELD29: "MOUNT GILEAD",
        FIELD30: "OH",
        co_postalCode: "43338",
        co_primaryPhoneNumber: "5732218372",
        co_monthlyIncome: "$3,766.00",
        co_mailingAddress: "",
        FIELD35: "",
        FIELD36: "",
        co_mailingPostalCode: "",
        auth_firstName: "",
        auth_middleInitial: "",
        auth_lastName: "",
        auth_suffix: "",
        auth_birthDate: "",
        auth_socialSecurityNumber: "",
        institutionName: "",
        bt_Amount: "",
        bt_Name: "",
        bt_MailingAdress: "",
        bt_PostalCode: "",
        institutionName2: "",
        bt_Amount2: "",
        bt_Name2: "",
        bt_MailingAdress2: "",
        bt_PostalCode2: "",
      },
  
      {
        creditResponsible: "JOINT",
        personalAmountCreditRequested: "1000",
        productName: "Rewards Platinum Visa®",
        FIELD4: "",
        firstName: "BEVERLY",
        middleInitial: "",
        lastName: "JEWETT",
        suffix: "",
        birthDate: "09171951",
        socialSecurityNumber: "666105246",
        address1: "10809 16TH AVE SE APT 312",
        FIELD12: "EVERETT",
        FIELD13: "WA",
        postalCode: "98208",
        mailingAddress: "",
        FIELD16: "",
        FIELD17: "",
        mailingPostalCode: "",
        primaryPhoneNumber: "4253574290",
        monthlyIncome: "$3,745.00",
        kba: "",
        co_firstName: "LINDA",
        co_middleInitial: "",
        co_lastName: "BATTON",
        co_suffix: "",
        co_birthDate: "11281961",
        co_socialSecurityNumber: "666592767",
        co_address1: "14166 POMONA AVE",
        FIELD29: "SPRING HILL ",
        FIELD30: "FL",
        co_postalCode: "34609",
        co_primaryPhoneNumber: "5734471108",
        co_monthlyIncome: "$6,001.00",
        co_mailingAddress: "4700 GOLDENEYE CT",
        FIELD35: "VIRGINIA BEACH",
        FIELD36: "VA",
        co_mailingPostalCode: "23462",
        auth_firstName: "",
        auth_middleInitial: "",
        auth_lastName: "",
        auth_suffix: "",
        auth_birthDate: "",
        auth_socialSecurityNumber: "",
        institutionName: "",
        bt_Amount: "",
        bt_Name: "",
        bt_MailingAdress: "",
        bt_PostalCode: "",
        institutionName2: "",
        bt_Amount2: "",
        bt_Name2: "",
        bt_MailingAdress2: "",
        bt_PostalCode2: "",
      },
      {
        creditResponsible: "JOINT",
        personalAmountCreditRequested: "1000",
        productName: "Visa® Signature Travel",
        FIELD4: "",
        firstName: "MILDRED",
        middleInitial: "M",
        lastName: "SANDER",
        suffix: "",
        birthDate: "01231943",
        socialSecurityNumber: "666104781",
        address1: "6436 S GARRISON CT",
        FIELD12: "LITTLETON",
        FIELD13: "CO",
        postalCode: "80123",
        mailingAddress: "",
        FIELD16: "",
        FIELD17: "",
        mailingPostalCode: "",
        primaryPhoneNumber: "3039483439",
        monthlyIncome: "$5,769.00",
        kba: "",
        co_firstName: "HENRY",
        co_middleInitial: "A",
        co_lastName: "BALLACCOMO",
        co_suffix: "",
        co_birthDate: "01271947",
        co_socialSecurityNumber: "666627510",
        co_address1: "539 E GRANT AVE",
        FIELD29: "ROSELLE PARK",
        FIELD30: "NJ",
        co_postalCode: "07204",
        co_primaryPhoneNumber: "7323505517",
        co_monthlyIncome: "$3,810.00",
        co_mailingAddress: "",
        FIELD35: "",
        FIELD36: "",
        co_mailingPostalCode: "",
        auth_firstName: "",
        auth_middleInitial: "",
        auth_lastName: "",
        auth_suffix: "",
        auth_birthDate: "",
        auth_socialSecurityNumber: "",
        institutionName: "",
        bt_Amount: "",
        bt_Name: "",
        bt_MailingAdress: "",
        bt_PostalCode: "",
        institutionName2: "",
        bt_Amount2: "",
        bt_Name2: "",
        bt_MailingAdress2: "",
        bt_PostalCode2: "",
      },
    ],
    organizations: [
      {
        industryType: "Finance and Insurance",
        industryCategory: "Insurance Carriers",
        //naicsCode is the "Industry - Specialty" field (not the actual Naics Code)
        naicsCode: "Direct Life Insurance Carriers",
        dateOfBusinessFormation: "12121950",
        yearsInBusiness: "lessThanOneYear",
        numberOfEmployees: "6",
        annualBusinessRevenue: "123123",
        amountCreditRequested: "25000",
        countryFormation: "Mexico",
        countryPrimaryActivity: "Canada",
        isJoint: "JOINT",
        product: "Business Edition Visa®",
        businessName: "HOLY CHURCH",
        businessStructure: "Corporation",
        taxIdentificationNumber: "45_1236140",
        businessPhysicalAddress: "12329",
        businessStreetName: "PINEHURST RD",
        businessCity: "BRICKTOWN",
        businessState: "NJ",
        businessPostalCode: "08723",
        amountCreditRequested: "$15,000.00",
        businessSpend: "$3,000",
        principal1FirstName: "RICHARD",
        principal1MI: "A",
        principal1LastName: "BRENNAN",
        principal1ResidentialAddress: "190 GRAY AVE 341",
        principal1City: "WAUKEE",
        principal1State: "IA",
        principal1ZipCode: 50263,
        principal1PrimaryPhone: 5159879665,
        principal1SSN: 666426588,
        principal1DOB: "08111927",
        principal1AnnualIncome: "$50,010.00",
        principal1SpendingLimit: "$1,000.00",
        principal2FirstName: "SHABNAM",
        principal2MI: "",
        principal2LastName: "MCCALLEY",
        principal2ResidentialAddress: "1097 GREYMOOR RD",
        principal2City: "SHOAL CREEK",
        principal2State: "AL",
        principal2ZipCode: 35242,
        principal2PrimaryPhone: 3014751668,
        principal2SSN: 666342015,
        principal2DOB: "09011947",
        principal2AnnualIncome: "$67,000.00",
        principal2SpendingLimit: "$100.00",
        principal3FirstName: "",
        principal3MI: "",
        principal3LastName: "",
        principal3ResidentialAddress: "",
        principal3City: "",
        principal3State: "",
        principal3ZipCode: null,
        principal3PrimaryPhone: null,
        principal3SSN: null,
        principal3DOB: "",
        principal3AnnualIncome: "",
        principal3SpendingLimit: "",
        principal4FirstName: "",
        principal4MI: "",
        principal4LastName: "",
        principal4ResidentialAddress: "",
        principal4City: "",
        principal4State: "",
        principal4ZipCode: null,
        principal4PrimaryPhone: null,
        principal4SSN: null,
        principal4DOB: "",
        principal4AnnualIncome: "",
        principal4SpendingLimit: "",
        beneficial1FirstName: "CATHY",
        beneficial1MI: "J",
        beneficial1LastName: "BELLAMY",
        beneficial1ResidentialAddress: "315 HUDSON AVE",
        beneficial1City: "STILLWATER",
        beneficial1State: "NY",
        beneficial1ZipCode: 12170,
        beneficial1SSN: 666426588,
        beneficial1DOB: "08111927",
        beneficial1SpendingLimit: "$1,000.00",
        beneficial2FirstName: "BERNARD",
        beneficial2LastName: "PELLECHIA",
        beneficial2MI: "",
        beneficial2ResidentialAddress: "30277 436TH AVE",
        beneficial2City: "UTICA",
        beneficial2State: "SD",
        beneficial2ZipCode: 57067,
        beneficial2PhoneNumber: 3014751668,
        beneficial2SSN: 666342015,
        beneficial2DOB: "09011947",
        beneficial2SpendingLimit: "$100.00",
        controllingFirstName: "THOMAS",
        controllingMI: "",
        controllingLastName: "BENSON",
        controllingResidentialAddress: "103 EMINENCE AVE",
        controllingCity: "HARRODSBURG",
        controllingState: "KY",
        controllingZipCode: 40330,
        controllingSSN: 666342015,
        controllingDOB: "09011947",
        controllingSpendingLimit: "$100.00",
        balanceTransfer1Institution: "",
        balanceTransfer1Amount: "",
        balanceTransfer1Name: "",
        balanceTransfer1Address: "",
        balanceTransfer1Account: "1234567890987",
        balanceTransfer2Institution: "",
        balanceTransfer2Amount: "",
        balanceTransfer2Name: "",
        balanceTransfer2Address: "",
        balanceTransfer2ZipCode: "",
        balanceTransfer2City: "",
        balanceTransfer2State: "",
        balanceTransfer2Account: "1234567890987",
        authorized1FirstName: "",
        authorized1MI: "",
        authorized1LastName: "",
        authorized1Suffix: "",
        authorized1DOB: "",
        authorized1SSN: null,
        authorized1SpendingLimit: "",
        authorized2FirstName: "",
        authorized2MI: "",
        authorized2LastName: "",
        authorized2Suffix: "",
        authorized2DOB: "",
        authorized2SSN: null,
        authorized2SpendingLimit: "",
      },
      {
        industryType: "Finance and Insurance",
        industryCategory: "Insurance Carriers",
        //naicsCode is the "Industry - Specialty" field (not the actual Naics Code)
        naicsCode: "Direct Life Insurance Carriers",
        dateOfBusinessFormation: "12121950",
        yearsInBusiness: "lessThanOneYear",
        numberOfEmployees: "6",
        annualBusinessRevenue: "123123",
        amountCreditRequested: "25000",
        countryFormation: "Mexico",
        countryPrimaryActivity: "Canada",
        isJoint: "",
        product: "Company Rewards Charge Card Visa®",
        businessName: "SUNNYSIDE MOBIL AUTO SHOP",
        businessStructure: "Corporation",
        taxIdentificationNumber: "45_4512426",
        businessPhysicalAddress: "11053",
        businessStreetName: "188TH LN",
        businessCity: "MORAGA",
        businessState: "CA",
        businessPostalCode: 94556,
        businessSpend: "$3,000",
        amountCreditRequested: "$10,000.00",
        principal1FirstName: "WILLIAM",
        principal1MI: "S",
        principal1LastName: "STATEN",
        principal1ResidentialAddress: "355 W JOLIET WHY",
        principal1City: "NEW LENOX",
        principal1State: "IL",
        principal1ZipCode: 60451,
        principal1PrimaryPhone: 8154634200,
        principal1SSN: 666673251,
        principal1DOB: 2121951,
        principal1AnnualIncome: "$127,000.00",
        principal1SpendingLimit: "$6,000.00",
        principal2FirstName: "",
        principal2MI: "",
        principal2LastName: "",
        principal2ResidentialAddress: "",
        principal2City: "",
        principal2State: "",
        principal2ZipCode: null,
        principal2PrimaryPhone: null,
        principal2SSN: null,
        principal2DOB: null,
        principal2AnnualIncome: "",
        principal2SpendingLimit: "",
        principal3FirstName: "",
        principal3MI: "",
        principal3LastName: "",
        principal3ResidentialAddress: "",
        principal3City: "",
        principal3State: "",
        principal3ZipCode: null,
        principal3PrimaryPhone: null,
        principal3SSN: null,
        principal3DOB: "",
        principal3AnnualIncome: "",
        principal3SpendingLimit: "",
        principal4FirstName: "",
        principal4MI: "",
        principal4LastName: "",
        principal4ResidentialAddress: "",
        principal4City: "",
        principal4State: "",
        principal4ZipCode: null,
        principal4PrimaryPhone: null,
        principal4SSN: null,
        principal4DOB: "",
        principal4AnnualIncome: "",
        principal4SpendingLimit: "",
        beneficial1FirstName: "DANNY",
        beneficial1MI: "C",
        beneficial1LastName: "DUNCAN",
        beneficial1ResidentialAddress: "12175 GLACIER HWY",
        beneficial1City: "JUNEAU",
        beneficial1State: "AK",
        beneficial1ZipCode: 99801,
        beneficial1SSN: 666673251,
        beneficial1DOB: 2121951,
        beneficial1SpendingLimit: "$6,000.00",
        beneficial2FirstName: "",
        beneficial2LastName: "",
        beneficial2MI: "",
        beneficial2ResidentialAddress: "",
        beneficial2City: "",
        beneficial2State: "",
        beneficial2ZipCode: null,
        beneficial2PhoneNumber: null,
        beneficial2SSN: null,
        beneficial2DOB: null,
        beneficial2SpendingLimit: "",
        controllingFirstName: "LISA",
        controllingMI: "S",
        controllingLastName: "FRANCIS",
        controllingResidentialAddress: "21175 WARDEN AVE",
        controllingCity: "ALLIANCE",
        controllingState: "OH",
        controllingZipCode: 44601,
        controllingSSN: 666673251,
        controllingDOB: "02121951",
        controllingSpendingLimit: "$6,000.00",
        balanceTransfer1Institution: "",
        balanceTransfer1Amount: "",
        balanceTransfer1Name: "",
        balanceTransfer1Address: "",
        balanceTransfer1Account: "1234567890987",
        balanceTransfer2Institution: "",
        balanceTransfer2Amount: "",
        balanceTransfer2Name: "",
        balanceTransfer2Address: "",
        balanceTransfer2ZipCode: "",
        balanceTransfer2City: "",
        balanceTransfer2State: "",
        balanceTransfer2Account: "1234567890987",
        authorized1FirstName: "",
        authorized1MI: "",
        authorized1LastName: "",
        authorized1Suffix: "",
        authorized1DOB: "",
        authorized1SSN: null,
        authorized1SpendingLimit: "",
        authorized2FirstName: "",
        authorized2MI: "",
        authorized2LastName: "",
        authorized2Suffix: "",
        authorized2DOB: "",
        authorized2SSN: null,
        authorized2SpendingLimit: "",
      },
      {
        industryType: "Finance and Insurance",
        industryCategory: "Insurance Carriers",
        //naicsCode is the "Industry - Specialty" field (not the actual Naics Code)
        naicsCode: "Direct Life Insurance Carriers",
        dateOfBusinessFormation: "12121950",
        yearsInBusiness: "lessThanOneYear",
        numberOfEmployees: "6",
        annualBusinessRevenue: "123123",
        amountCreditRequested: "25000",
        countryFormation: "Mexico",
        countryPrimaryActivity: "Canada",
        isJoint: "",
        product: "Business Edition Visa®",
        businessName: "GLOBAL NEEDS",
        businessStructure: "Corporation",
        taxIdentificationNumber: "45_4512424",
        businessPhysicalAddress: "11051",
        businessStreetName: "CHERYL DR",
        businessCity: "MORAGA",
        businessState: "CA",
        businessPostalCode: 94556,
        businessSpend: "$3,000",
        amountCreditRequested: "$1,200.00",
        principal1FirstName: "SHIRLEY",
        principal1MI: "",
        principal1LastName: "SCHROEDER",
        principal1ResidentialAddress: "75 NORTHWOOD DR",
        principal1City: "DOYLESTOWN",
        principal1State: "OH",
        principal1ZipCode: 44230,
        principal1PrimaryPhone: 3306580707,
        principal1SSN: 666591414,
        principal1DOB: 4041960,
        principal1AnnualIncome: "$45,000.00",
        principal1SpendingLimit: "$100.00",
        principal2FirstName: "",
        principal2MI: "",
        principal2LastName: "",
        principal2ResidentialAddress: "",
        principal2City: "",
        principal2State: "",
        principal2ZipCode: null,
        principal2PrimaryPhone: null,
        principal2SSN: null,
        principal2DOB: null,
        principal2AnnualIncome: "",
        principal2SpendingLimit: "",
        principal3FirstName: "",
        principal3MI: "",
        principal3LastName: "",
        principal3ResidentialAddress: "",
        principal3City: "",
        principal3State: "",
        principal3ZipCode: null,
        principal3PrimaryPhone: null,
        principal3SSN: null,
        principal3DOB: "",
        principal3AnnualIncome: "",
        principal3SpendingLimit: "",
        principal4FirstName: "",
        principal4MI: "",
        principal4LastName: "",
        principal4ResidentialAddress: "",
        principal4City: "",
        principal4State: "",
        principal4ZipCode: null,
        principal4PrimaryPhone: null,
        principal4SSN: null,
        principal4DOB: "",
        principal4AnnualIncome: "",
        principal4SpendingLimit: "",
        beneficial1FirstName: "TINA",
        beneficial1MI: "",
        beneficial1LastName: "BRYANT",
        beneficial1ResidentialAddress: "18 ALESIA DR",
        beneficial1City: "EAST PRAIRIE",
        beneficial1State: "MO",
        beneficial1ZipCode: 63845,
        beneficial1SSN: 666591414,
        beneficial1DOB: 4041960,
        beneficial1SpendingLimit: "$100.00",
        beneficial2FirstName: "",
        beneficial2LastName: "",
        beneficial2MI: "",
        beneficial2ResidentialAddress: "",
        beneficial2City: "",
        beneficial2State: "",
        beneficial2ZipCode: null,
        beneficial2PhoneNumber: null,
        beneficial2SSN: null,
        beneficial2DOB: null,
        beneficial2SpendingLimit: "",
        controllingFirstName: "DAVID",
        controllingMI: "A",
        controllingLastName: "SULLINS",
        controllingResidentialAddress: "3535 RUNNYMEDE RD",
        controllingCity: "TANEYTOWN",
        controllingState: "MD",
        controllingZipCode: 21787,
        controllingSSN: 666591414,
        controllingDOB: "04041960",
        controllingSpendingLimit: "$100.00",
        balanceTransfer1Institution: "",
        balanceTransfer1Amount: "",
        balanceTransfer1Name: "",
        balanceTransfer1Address: "",
        balanceTransfer1Account: "1234567890987",
        balanceTransfer2Institution: "",
        balanceTransfer2Amount: "",
        balanceTransfer2Name: "",
        balanceTransfer2Address: "",
        balanceTransfer2ZipCode: "",
        balanceTransfer2City: "",
        balanceTransfer2State: "",
        balanceTransfer2Account: "1234567890987",
        authorized1FirstName: "",
        authorized1MI: "",
        authorized1LastName: "",
        authorized1Suffix: "",
        authorized1DOB: "",
        authorized1SSN: null,
        authorized1SpendingLimit: "",
        authorized2FirstName: "",
        authorized2MI: "",
        authorized2LastName: "",
        authorized2Suffix: "",
        authorized2DOB: "",
        authorized2SSN: null,
        authorized2SpendingLimit: "",
      },
      {
        industryType: "Finance and Insurance",
        industryCategory: "Insurance Carriers",
        //naicsCode is the "Industry - Specialty" field (not the actual Naics Code)
        naicsCode: "Direct Life Insurance Carriers",
        dateOfBusinessFormation: "12121950",
        yearsInBusiness: "lessThanOneYear",
        numberOfEmployees: "6",
        annualBusinessRevenue: "123123",
        amountCreditRequested: "25000",
        countryFormation: "Mexico",
        countryPrimaryActivity: "Canada",
        isJoint: "",
        product: "Business Rewards Visa®",
        businessName: "KENTUCKY PAINTERS",
        businessStructure: "Corporation",
        taxIdentificationNumber: "23_1472589",
        businessPhysicalAddress: "11236",
        businessStreetName: "ABDMORE AVE",
        businessCity: "VIRGINIA BEACH",
        businessState: "VA",
        businessPostalCode: 23452,
        businessSpend: "$3,000",
        amountCreditRequested: "$25,000.00",
        principal1FirstName: "THOMAS",
        principal1MI: "",
        principal1LastName: "RETTEW",
        principal1ResidentialAddress: "1642 W MONTEROSA ST",
        principal1City: "PHOENIX",
        principal1State: "AZ",
        principal1ZipCode: 85015,
        principal1PrimaryPhone: 6022962281,
        principal1SSN: 666075897,
        principal1DOB: 5231972,
        principal1AnnualIncome: "$57,000.00",
        principal1SpendingLimit: "$100.00",
        principal2FirstName: "",
        principal2MI: "",
        principal2LastName: "",
        principal2ResidentialAddress: "",
        principal2City: "",
        principal2State: "",
        principal2ZipCode: null,
        principal2PrimaryPhone: null,
        principal2SSN: null,
        principal2DOB: null,
        principal2AnnualIncome: "",
        principal2SpendingLimit: "",
        principal3FirstName: "",
        principal3MI: "",
        principal3LastName: "",
        principal3ResidentialAddress: "",
        principal3City: "",
        principal3State: "",
        principal3ZipCode: null,
        principal3PrimaryPhone: null,
        principal3SSN: null,
        principal3DOB: "",
        principal3AnnualIncome: "",
        principal3SpendingLimit: "",
        principal4FirstName: "",
        principal4MI: "",
        principal4LastName: "",
        principal4ResidentialAddress: "",
        principal4City: "",
        principal4State: "",
        principal4ZipCode: null,
        principal4PrimaryPhone: null,
        principal4SSN: null,
        principal4DOB: "",
        principal4AnnualIncome: "",
        principal4SpendingLimit: "",
        beneficial1FirstName: "THOMAS",
        beneficial1MI: "",
        beneficial1LastName: "RETTEW",
        beneficial1ResidentialAddress: "1642 W MONTEROSA ST",
        beneficial1City: "PHOENIX",
        beneficial1State: "AZ",
        beneficial1ZipCode: 85015,
        beneficial1SSN: 666075897,
        beneficial1DOB: 5231972,
        beneficial1SpendingLimit: "$100.00",
        beneficial2FirstName: "",
        beneficial2LastName: "",
        beneficial2MI: "",
        beneficial2ResidentialAddress: "",
        beneficial2City: "",
        beneficial2State: "",
        beneficial2ZipCode: null,
        beneficial2PhoneNumber: null,
        beneficial2SSN: null,
        beneficial2DOB: null,
        beneficial2SpendingLimit: "",
        controllingFirstName: "GUSS",
        controllingMI: "",
        controllingLastName: "LEE",
        controllingResidentialAddress: "1700 1ST AVE ",
        controllingCity: "ABBEVILLE",
        controllingState: "AL",
        controllingZipCode: 36310,
        controllingSSN: 666999992,
        controllingDOB: "09121957",
        controllingSpendingLimit: "$0.00",
        balanceTransfer1Institution: "",
        balanceTransfer1Amount: "",
        balanceTransfer1Name: "",
        balanceTransfer1Address: "",
        balanceTransfer1Account: "1234567890987",
        balanceTransfer2Institution: "",
        balanceTransfer2Amount: "",
        balanceTransfer2Name: "",
        balanceTransfer2Address: "",
        balanceTransfer2ZipCode: "",
        balanceTransfer2City: "",
        balanceTransfer2State: "",
        balanceTransfer2Account: "1234567890987",
        authorized1FirstName: "",
        authorized1MI: "",
        authorized1LastName: "",
        authorized1Suffix: "",
        authorized1DOB: "",
        authorized1SSN: null,
        authorized1SpendingLimit: "",
        authorized2FirstName: "",
        authorized2MI: "",
        authorized2LastName: "",
        authorized2Suffix: "",
        authorized2DOB: "",
        authorized2SSN: null,
        authorized2SpendingLimit: "",
      },
      {
        industryType: "Finance and Insurance",
        industryCategory: "Insurance Carriers",
        //naicsCode is the "Industry - Specialty" field (not the actual Naics Code)
        naicsCode: "Direct Life Insurance Carriers",
        dateOfBusinessFormation: "12121950",
        yearsInBusiness: "lessThanOneYear",
        numberOfEmployees: "6",
        annualBusinessRevenue: "123123",
        amountCreditRequested: "25000",
        countryFormation: "Mexico",
        countryPrimaryActivity: "Canada",
        isJoint: "",
        product: "Business Rewards Visa®",
        businessName: "MERIDIAN BAY MANAGEMENT",
        businessStructure: "Corporation",
        taxIdentificationNumber: "45_1236123",
        businessPhysicalAddress: "12312",
        businessStreetName: "THOMAS NELSON DR",
        businessCity: "VIRGINIA BEACH",
        businessState: "VA",
        businessPostalCode: 23452,
        businessSpend: "$3,000",
        amountCreditRequested: "$6,000.00",
        principal1FirstName: "DAVID",
        principal1MI: "G",
        principal1LastName: "SULLINS",
        principal1ResidentialAddress: "3535 RUNNYMEDE RD",
        principal1City: "TANEYTOWN",
        principal1State: "MD",
        principal1ZipCode: 21787,
        principal1PrimaryPhone: 4107568433,
        principal1SSN: 666284895,
        principal1DOB: "08111972",
        principal1AnnualIncome: "$60,000.00",
        principal1SpendingLimit: "$5,000.00",
        principal2FirstName: "",
        principal2MI: "",
        principal2LastName: "",
        principal2ResidentialAddress: "",
        principal2City: "",
        principal2State: "",
        principal2ZipCode: null,
        principal2PrimaryPhone: null,
        principal2SSN: null,
        principal2DOB: null,
        principal2AnnualIncome: "",
        principal2SpendingLimit: "",
        principal3FirstName: "",
        principal3MI: "",
        principal3LastName: "",
        principal3ResidentialAddress: "",
        principal3City: "",
        principal3State: "",
        principal3ZipCode: null,
        principal3PrimaryPhone: null,
        principal3SSN: null,
        principal3DOB: "",
        principal3AnnualIncome: "",
        principal3SpendingLimit: "",
        principal4FirstName: "",
        principal4MI: "",
        principal4LastName: "",
        principal4ResidentialAddress: "",
        principal4City: "",
        principal4State: "",
        principal4ZipCode: null,
        principal4PrimaryPhone: null,
        principal4SSN: null,
        principal4DOB: "",
        principal4AnnualIncome: "",
        principal4SpendingLimit: "",
        beneficial1FirstName: "IRIS",
        beneficial1MI: "G",
        beneficial1LastName: "TILLMAN",
        beneficial1ResidentialAddress: "417 REED AVE",
        beneficial1City: "TANEYTOWN",
        beneficial1State: "MD",
        beneficial1ZipCode: 21787,
        beneficial1SSN: 666284895,
        beneficial1DOB: "08111972",
        beneficial1SpendingLimit: "$5,000.00",
        beneficial2FirstName: "JOHN ",
        beneficial2LastName: "SMITH",
        beneficial2MI: "",
        beneficial2ResidentialAddress: "71 SMITH STREET",
        beneficial2City: "SALINA",
        beneficial2State: "KS",
        beneficial2ZipCode: 67401,
        beneficial2PhoneNumber: 3016661712,
        beneficial2SSN: 666123147,
        beneficial2DOB: "11011971",
        beneficial2SpendingLimit: "$0.00",
        controllingFirstName: "KATHLEEN",
        controllingMI: "",
        controllingLastName: "MASON",
        controllingResidentialAddress: "3711 CANAL BLVD",
        controllingCity: "TAMPA",
        controllingState: "FL",
        controllingZipCode: 33635,
        controllingSSN: 666771717,
        controllingDOB: "09241982",
        controllingSpendingLimit: "$0.00",
        balanceTransfer1Institution: "",
        balanceTransfer1Amount: "",
        balanceTransfer1Name: "",
        balanceTransfer1Address: "",
        balanceTransfer1Account: "1234567890987",
        balanceTransfer2Institution: "",
        balanceTransfer2Amount: "",
        balanceTransfer2Name: "",
        balanceTransfer2Address: "",
        balanceTransfer2ZipCode: "",
        balanceTransfer2City: "",
        balanceTransfer2State: "",
        balanceTransfer2Account: "1234567890987",
        authorized1FirstName: "",
        authorized1MI: "",
        authorized1LastName: "",
        authorized1Suffix: "",
        authorized1DOB: "",
        authorized1SSN: null,
        authorized1SpendingLimit: "",
        authorized2FirstName: "",
        authorized2MI: "",
        authorized2LastName: "",
        authorized2Suffix: "",
        authorized2DOB: "",
        authorized2SSN: null,
        authorized2SpendingLimit: "",
      },
      {
        industryType: "Finance and Insurance",
        industryCategory: "Insurance Carriers",
        //naicsCode is the "Industry - Specialty" field (not the actual Naics Code)
        naicsCode: "Direct Life Insurance Carriers",
        dateOfBusinessFormation: "12121950",
        yearsInBusiness: "lessThanOneYear",
        numberOfEmployees: "6",
        annualBusinessRevenue: "123123",
        amountCreditRequested: "25000",
        countryFormation: "Mexico",
        countryPrimaryActivity: "Canada",
        isJoint: "JOINT",
        product: "Business Edition Visa®",
        businessName: "HOLY CHURCH",
        businessStructure: "Corporation",
        taxIdentificationNumber: "45_1236140",
        businessPhysicalAddress: "12329",
        businessStreetName: "PINEHURST RD",
        businessCity: "BRICKTOWN",
        businessState: "NJ",
        businessPostalCode: "08723",
        businessSpend: "$3,000",
        amountCreditRequested: "$15,000.00",
        principal1FirstName: "RICHARD",
        principal1MI: "A",
        principal1LastName: "BRENNAN",
        principal1ResidentialAddress: "190 GRAY AVE 341",
        principal1City: "WAUKEE",
        principal1State: "IA",
        principal1ZipCode: 50263,
        principal1PrimaryPhone: 5159879665,
        principal1SSN: 666426588,
        principal1DOB: "08111927",
        principal1AnnualIncome: "$50,010.00",
        principal1SpendingLimit: "$1,000.00",
        principal2FirstName: "BERNARD",
        principal2MI: "",
        principal2LastName: "HOWARD",
        principal2ResidentialAddress: "40522 PORT PL",
        principal2City: "LEONARDTOWN",
        principal2State: "MD",
        principal2ZipCode: 20650,
        principal2PrimaryPhone: 3014751668,
        principal2SSN: 666342015,
        principal2DOB: "09011947",
        principal2AnnualIncome: "$67,000.00",
        principal2SpendingLimit: "$100.00",
        principal3FirstName: "",
        principal3MI: "",
        principal3LastName: "",
        principal3ResidentialAddress: "",
        principal3City: "",
        principal3State: "",
        principal3ZipCode: null,
        principal3PrimaryPhone: null,
        principal3SSN: null,
        principal3DOB: "",
        principal3AnnualIncome: "",
        principal3SpendingLimit: "",
        principal4FirstName: "",
        principal4MI: "",
        principal4LastName: "",
        principal4ResidentialAddress: "",
        principal4City: "",
        principal4State: "",
        principal4ZipCode: null,
        principal4PrimaryPhone: null,
        principal4SSN: null,
        principal4DOB: "",
        principal4AnnualIncome: "",
        principal4SpendingLimit: "",
        beneficial1FirstName: "WILLIAM",
        beneficial1MI: "A",
        beneficial1LastName: "STATEN",
        beneficial1ResidentialAddress: "355 W JOLIET WHY",
        beneficial1City: "NEW LENOX",
        beneficial1State: "IL",
        beneficial1ZipCode: 60451,
        beneficial1SSN: 666426588,
        beneficial1DOB: "08111927",
        beneficial1SpendingLimit: "$1,000.00",
        beneficial2FirstName: "BERNARD",
        beneficial2LastName: "HOWARD",
        beneficial2MI: "",
        beneficial2ResidentialAddress: "40522 PORT PL",
        beneficial2City: "LEONARDTOWN",
        beneficial2State: "MD",
        beneficial2ZipCode: 20650,
        beneficial2PhoneNumber: 3014751668,
        beneficial2SSN: 666342015,
        beneficial2DOB: "09011947",
        beneficial2SpendingLimit: "$100.00",
        controllingFirstName: "JOHN",
        controllingMI: "",
        controllingLastName: "BARTON",
        controllingResidentialAddress: "8166 COUNTRY BAY BLVD",
        controllingCity: "NAVARRE",
        controllingState: "MD",
        controllingZipCode: 32566,
        controllingSSN: 666342015,
        controllingDOB: "09011947",
        controllingSpendingLimit: "$100.00",
        balanceTransfer1Institution: "",
        balanceTransfer1Amount: "",
        balanceTransfer1Name: "",
        balanceTransfer1Address: "",
        balanceTransfer1Account: "1234567890987",
        balanceTransfer2Institution: "",
        balanceTransfer2Amount: "",
        balanceTransfer2Name: "",
        balanceTransfer2Address: "",
        balanceTransfer2ZipCode: "",
        balanceTransfer2City: "",
        balanceTransfer2State: "",
        balanceTransfer2Account: "1234567890987",
        authorized1FirstName: "",
        authorized1MI: "",
        authorized1LastName: "",
        authorized1Suffix: "",
        authorized1DOB: "",
        authorized1SSN: null,
        authorized1SpendingLimit: "",
        authorized2FirstName: "",
        authorized2MI: "",
        authorized2LastName: "",
        authorized2Suffix: "",
        authorized2DOB: "",
        authorized2SSN: null,
        authorized2SpendingLimit: "",
      },
      {
        industryType: "Finance and Insurance",
        industryCategory: "Insurance Carriers",
        //naicsCode is the "Industry - Specialty" field (not the actual Naics Code)
        naicsCode: "Direct Life Insurance Carriers",
        dateOfBusinessFormation: "12121950",
        yearsInBusiness: "lessThanOneYear",
        numberOfEmployees: "6",
        annualBusinessRevenue: "123123",
        amountCreditRequested: "25000",
        countryFormation: "Mexico",
        countryPrimaryActivity: "Canada",
        isJoint: "JOINT",
        product: "Company Rewards Charge Card Visa®",
        businessName: "RB RANCH",
        businessStructure: "Corporation",
        taxIdentificationNumber: "45_1236154",
        businessPhysicalAddress: "12343",
        businessStreetName: "BALDWIN DR",
        businessCity: "FORKED RIVER",
        businessState: "NJ",
        businessPostalCode: "08731",
        businessSpend: "$3,000",
        amountCreditRequested: "$10,000.00",
        principal1FirstName: "TINA",
        principal1MI: "",
        principal1LastName: "BRYANT",
        principal1ResidentialAddress: "18 ALESIA DR",
        principal1City: "EAST PRAIRIE",
        principal1State: "MO",
        principal1ZipCode: 63845,
        principal1PrimaryPhone: 5736490741,
        principal1SSN: 666438066,
        principal1DOB: 8211962,
        principal1AnnualIncome: "$140,000.00",
        principal1SpendingLimit: "$100.00",
        principal2FirstName: "DONITA",
        principal2MI: "S",
        principal2LastName: "COLETTE",
        principal2ResidentialAddress: "3608 COPLEY RD",
        principal2City: "HERMANTOWN",
        principal2State: "MN",
        principal2ZipCode: 55811,
        principal2PrimaryPhone: 2187208972,
        principal2SSN: 666366222,
        principal2DOB: 08011950,
        principal2AnnualIncome: "$3,711.00",
        principal2SpendingLimit: "$1,000.00",
        principal3FirstName: "",
        principal3MI: "",
        principal3LastName: "",
        principal3ResidentialAddress: "",
        principal3City: "",
        principal3State: "",
        principal3ZipCode: null,
        principal3PrimaryPhone: null,
        principal3SSN: null,
        principal3DOB: "",
        principal3AnnualIncome: "",
        principal3SpendingLimit: "",
        principal4FirstName: "",
        principal4MI: "",
        principal4LastName: "",
        principal4ResidentialAddress: "",
        principal4City: "",
        principal4State: "",
        principal4ZipCode: null,
        principal4PrimaryPhone: null,
        principal4SSN: null,
        principal4DOB: "",
        principal4AnnualIncome: "",
        principal4SpendingLimit: "",
        beneficial1FirstName: "TINA",
        beneficial1MI: "",
        beneficial1LastName: "BRYANT",
        beneficial1ResidentialAddress: "18 ALESIA DR",
        beneficial1City: "EAST PRAIRIE",
        beneficial1State: "MO",
        beneficial1ZipCode: 63845,
        beneficial1SSN: 666438066,
        beneficial1DOB: 8211962,
        beneficial1SpendingLimit: "$100.00",
        beneficial2FirstName: "DONITA",
        beneficial2LastName: "COLETTE",
        beneficial2MI: "S",
        beneficial2ResidentialAddress: "3608 COPLEY RD",
        beneficial2City: "HERMANTOWN",
        beneficial2State: "MN",
        beneficial2ZipCode: 55811,
        beneficial2PhoneNumber: 2187208972,
        beneficial2SSN: 666366222,
        beneficial2DOB: 8011950,
        beneficial2SpendingLimit: "$1,000.00",
        controllingFirstName: "DONITA",
        controllingMI: "",
        controllingLastName: "COLETTE",
        controllingResidentialAddress: "3608 COPLEY RD",
        controllingCity: "HERMANTOWN",
        controllingState: "MN",
        controllingZipCode: 55811,
        controllingSSN: 666366222,
        controllingDOB: "08011950",
        controllingSpendingLimit: "$1,000.00",
        balanceTransfer1Institution: "",
        balanceTransfer1Amount: "",
        balanceTransfer1Name: "",
        balanceTransfer1Address: "",
        balanceTransfer1Account: "1234567890987",
        balanceTransfer2Institution: "",
        balanceTransfer2Amount: "",
        balanceTransfer2Name: "",
        balanceTransfer2Address: "",
        balanceTransfer2ZipCode: "",
        balanceTransfer2City: "",
        balanceTransfer2State: "",
        balanceTransfer2Account: "1234567890987",
        authorized1FirstName: "",
        authorized1MI: "",
        authorized1LastName: "",
        authorized1Suffix: "",
        authorized1DOB: "",
        authorized1SSN: null,
        authorized1SpendingLimit: "",
        authorized2FirstName: "",
        authorized2MI: "",
        authorized2LastName: "",
        authorized2Suffix: "",
        authorized2DOB: "",
        authorized2SSN: null,
        authorized2SpendingLimit: "",
      },
      {
        industryType: "Finance and Insurance",
        industryCategory: "Insurance Carriers",
        //naicsCode is the "Industry - Specialty" field (not the actual Naics Code)
        naicsCode: "Direct Life Insurance Carriers",
        dateOfBusinessFormation: "12121950",
        yearsInBusiness: "lessThanOneYear",
        numberOfEmployees: "6",
        annualBusinessRevenue: "123123",
        amountCreditRequested: "25000",
        countryFormation: "Mexico",
        countryPrimaryActivity: "Canada",
        isJoint: "JOINT",
        product: "Business Cash Rewards Visa®",
        businessName: "SS FARMS",
        businessStructure: "Corporation",
        taxIdentificationNumber: "45_1236152",
        businessPhysicalAddress: "12341",
        businessStreetName: "TWIN OAKS RD",
        businessCity: "FORKED RIVER",
        businessState: "NJ",
        businessPostalCode: "08731",
        businessSpend: "$3,000",
        amountCreditRequested: "$7,000.00",
        principal1FirstName: "BOBBIJO",
        principal1MI: "",
        principal1LastName: "MUNRO",
        principal1ResidentialAddress: "3 CALVIN LN 379",
        principal1City: "SIKESTON",
        principal1State: "MO",
        principal1ZipCode: 63801,
        principal1PrimaryPhone: 5734710434,
        principal1SSN: 666165714,
        principal1DOB: 3091948,
        principal1AnnualIncome: "$75,000.00",
        principal1SpendingLimit: "$1,000.00",
        principal2FirstName: "DLYDE",
        principal2MI: "m  ",
        principal2LastName: "SMITH",
        principal2ResidentialAddress: "3677 US HIGHWAY 23",
        principal2City: "CHILLICOTHE",
        principal2State: "OH",
        principal2ZipCode: 45601,
        principal2PrimaryPhone: 7407036189,
        principal2SSN: 666020655,
        principal2DOB: 10171964,
        principal2AnnualIncome: "$6,711.00",
        principal2SpendingLimit: "$1,000.00",
        principal3FirstName: "",
        principal3MI: "",
        principal3LastName: "",
        principal3ResidentialAddress: "",
        principal3City: "",
        principal3State: "",
        principal3ZipCode: null,
        principal3PrimaryPhone: null,
        principal3SSN: null,
        principal3DOB: "",
        principal3AnnualIncome: "",
        principal3SpendingLimit: "",
        principal4FirstName: "",
        principal4MI: "",
        principal4LastName: "",
        principal4ResidentialAddress: "",
        principal4City: "",
        principal4State: "",
        principal4ZipCode: null,
        principal4PrimaryPhone: null,
        principal4SSN: null,
        principal4DOB: "",
        principal4AnnualIncome: "",
        principal4SpendingLimit: "",
        beneficial1FirstName: "BOBBIJO",
        beneficial1MI: "",
        beneficial1LastName: "MUNRO",
        beneficial1ResidentialAddress: "3 CALVIN LN 379",
        beneficial1City: "SIKESTON",
        beneficial1State: "MO",
        beneficial1ZipCode: 63801,
        beneficial1SSN: 666165714,
        beneficial1DOB: 3091948,
        beneficial1SpendingLimit: "$1,000.00",
        beneficial2FirstName: "DLYDE",
        beneficial2LastName: "SMITH",
        beneficial2MI: "Middle Initial",
        beneficial2ResidentialAddress: "3677 US HIGHWAY 23",
        beneficial2City: "CHILLICOTHE",
        beneficial2State: "OH",
        beneficial2ZipCode: 45601,
        beneficial2PhoneNumber: 7407036189,
        beneficial2SSN: 666020655,
        beneficial2DOB: 10171964,
        beneficial2SpendingLimit: "$1,000.00",
        controllingFirstName: "DLYDE",
        controllingMI: "",
        controllingLastName: "SMITH",
        controllingResidentialAddress: "3677 US HIGHWAY 23",
        controllingCity: "CHILLICOTHE",
        controllingState: "OH",
        controllingZipCode: 45601,
        controllingSSN: 666020655,
        controllingDOB: "10171964",
        controllingSpendingLimit: "$1,000.00",
        balanceTransfer1Institution: "",
        balanceTransfer1Amount: "",
        balanceTransfer1Name: "",
        balanceTransfer1Address: "",
        balanceTransfer1Account: "1234567890987",
        balanceTransfer2Institution: "",
        balanceTransfer2Amount: "",
        balanceTransfer2Name: "",
        balanceTransfer2Address: "",
        balanceTransfer2ZipCode: "",
        balanceTransfer2City: "",
        balanceTransfer2State: "",
        balanceTransfer2Account: "1234567890987",
        authorized1FirstName: "",
        authorized1MI: "",
        authorized1LastName: "",
        authorized1Suffix: "",
        authorized1DOB: "",
        authorized1SSN: null,
        authorized1SpendingLimit: "",
        authorized2FirstName: "",
        authorized2MI: "",
        authorized2LastName: "",
        authorized2Suffix: "",
        authorized2DOB: "",
        authorized2SSN: null,
        authorized2SpendingLimit: "",
      },
      {
        industryType: "Finance and Insurance",
        industryCategory: "Insurance Carriers",
        //naicsCode is the "Industry - Specialty" field (not the actual Naics Code)
        naicsCode: "Direct Life Insurance Carriers",
        dateOfBusinessFormation: "12121950",
        yearsInBusiness: "lessThanOneYear",
        numberOfEmployees: "6",
        annualBusinessRevenue: "123123",
        amountCreditRequested: "25000",
        countryFormation: "Mexico",
        countryPrimaryActivity: "Canada",
        isJoint: "",
  
        product: "Business Rewards Visa®",
        businessName: "BANK OF GEORGIA",
        businessStructure: "Corporation",
        taxIdentificationNumber: "45_1236149",
        businessPhysicalAddress: "12338",
        businessStreetName: "LKINGEL RD",
        businessCity: "PROSPECT ",
        businessState: "OH",
        businessPostalCode: 43342,
        businessSpend: "$3,000",
        amountCreditRequested: "$78,000.00",
        principal1FirstName: "KEITH",
        principal1MI: "",
        principal1LastName: "LEE",
        principal1ResidentialAddress: "36 WESTDALE DR",
        principal1City: "HOWELL",
        principal1State: "MI",
        principal1ZipCode: 48843,
        principal1PrimaryPhone: 5175462410,
        principal1SSN: 666468015,
        principal1DOB: 6291951,
        principal1AnnualIncome: "$123,699.00",
        principal1SpendingLimit: "$25,000.00",
        principal2FirstName: "",
        principal2MI: "",
        principal2LastName: "",
        principal2ResidentialAddress: "",
        principal2City: "",
        principal2State: "",
        principal2ZipCode: null,
        principal2PrimaryPhone: null,
        principal2SSN: null,
        principal2DOB: null,
        principal2AnnualIncome: "",
        principal2SpendingLimit: "",
        principal3FirstName: "",
        principal3MI: "",
        principal3LastName: "",
        principal3ResidentialAddress: "",
        principal3City: "",
        principal3State: "",
        principal3ZipCode: null,
        principal3PrimaryPhone: null,
        principal3SSN: null,
        principal3DOB: "",
        principal3AnnualIncome: "",
        principal3SpendingLimit: "",
        principal4FirstName: "",
        principal4MI: "",
        principal4LastName: "",
        principal4ResidentialAddress: "",
        principal4City: "",
        principal4State: "",
        principal4ZipCode: null,
        principal4PrimaryPhone: null,
        principal4SSN: null,
        principal4DOB: "",
        principal4AnnualIncome: "",
        principal4SpendingLimit: "",
        beneficial1FirstName: "TOMMY",
        beneficial1MI: "",
        beneficial1LastName: "LEE",
        beneficial1ResidentialAddress: "36 WESTDALE DR",
        beneficial1City: "HOWELL",
        beneficial1State: "MI",
        beneficial1ZipCode: 48843,
        beneficial1SSN: 666468015,
        beneficial1DOB: 6291951,
        beneficial1SpendingLimit: "$25,000.00",
        beneficial2FirstName: "",
        beneficial2LastName: "",
        beneficial2MI: "",
        beneficial2ResidentialAddress: "",
        beneficial2City: "",
        beneficial2State: "",
        beneficial2ZipCode: null,
        beneficial2PhoneNumber: null,
        beneficial2SSN: null,
        beneficial2DOB: null,
        beneficial2SpendingLimit: "",
        controllingFirstName: "KENNY",
        controllingMI: "",
        controllingLastName: "LEE",
        controllingResidentialAddress: "36 WESTDALE DR",
        controllingCity: "HOWELL",
        controllingState: "MI",
        controllingZipCode: 48843,
        controllingSSN: 666468015,
        controllingDOB: "06291951",
        controllingSpendingLimit: "$25,000.00",
        balanceTransfer1Institution: "",
        balanceTransfer1Amount: "",
        balanceTransfer1Name: "",
        balanceTransfer1Address: "",
        balanceTransfer1Account: "1234567890987",
        balanceTransfer2Institution: "",
        balanceTransfer2Amount: "",
        balanceTransfer2Name: "",
        balanceTransfer2Address: "",
        balanceTransfer2ZipCode: "",
        balanceTransfer2City: "",
        balanceTransfer2State: "",
        balanceTransfer2Account: "1234567890987",
        authorized1FirstName: "",
        authorized1MI: "",
        authorized1LastName: "",
        authorized1Suffix: "",
        authorized1DOB: "",
        authorized1SSN: null,
        authorized1SpendingLimit: "",
        authorized2FirstName: "",
        authorized2MI: "",
        authorized2LastName: "",
        authorized2Suffix: "",
        authorized2DOB: "",
        authorized2SSN: null,
        authorized2SpendingLimit: "",
      },
      {
        industryType: "Finance and Insurance",
        industryCategory: "Insurance Carriers",
        //naicsCode is the "Industry - Specialty" field (not the actual Naics Code)
        naicsCode: "Direct Life Insurance Carriers",
        dateOfBusinessFormation: "12121950",
        yearsInBusiness: "lessThanOneYear",
        numberOfEmployees: "6",
        annualBusinessRevenue: "123123",
        amountCreditRequested: "25000",
        countryFormation: "Mexico",
        countryPrimaryActivity: "Canada",
        isJoint: "",
  
        product: "Business Edition Visa®",
        businessName: "IRON UNITED TRUCKING",
        businessStructure: "Corporation",
        taxIdentificationNumber: "45_1236144",
        businessPhysicalAddress: "12333",
        businessStreetName: "PARK BLVD",
        businessCity: "MARION ",
        businessState: "OH",
        businessPostalCode: 43302,
        businessSpend: "$3,000",
        amountCreditRequested: "$27,000.00",
        principal1FirstName: "DANIELLE",
        principal1MI: "A",
        principal1LastName: "BUSCHER",
        principal1ResidentialAddress: "2 JULIET LN APT 104",
        principal1City: "BALTIMORE",
        principal1State: "MD",
        principal1ZipCode: 21236,
        principal1PrimaryPhone: 4105298138,
        principal1SSN: 666535554,
        principal1DOB: 12181970,
        principal1AnnualIncome: "$23,250.00",
        principal1SpendingLimit: "$2,000.00",
        principal2FirstName: "",
        principal2MI: "",
        principal2LastName: "",
        principal2ResidentialAddress: "",
        principal2City: "",
        principal2State: "",
        principal2ZipCode: null,
        principal2PrimaryPhone: null,
        principal2SSN: null,
        principal2DOB: null,
        principal2AnnualIncome: "",
        principal2SpendingLimit: "",
        principal3FirstName: "",
        principal3MI: "",
        principal3LastName: "",
        principal3ResidentialAddress: "",
        principal3City: "",
        principal3State: "",
        principal3ZipCode: null,
        principal3PrimaryPhone: null,
        principal3SSN: null,
        principal3DOB: "",
        principal3AnnualIncome: "",
        principal3SpendingLimit: "",
        principal4FirstName: "",
        principal4MI: "",
        principal4LastName: "",
        principal4ResidentialAddress: "",
        principal4City: "",
        principal4State: "",
        principal4ZipCode: null,
        principal4PrimaryPhone: null,
        principal4SSN: null,
        principal4DOB: "",
        principal4AnnualIncome: "",
        principal4SpendingLimit: "",
        beneficial1FirstName: "DANIELLE",
        beneficial1MI: "A",
        beneficial1LastName: "BUSCHER",
        beneficial1ResidentialAddress: "2 JULIET LN APT 104",
        beneficial1City: "BALTIMORE",
        beneficial1State: "MD",
        beneficial1ZipCode: 21236,
        beneficial1SSN: 666535554,
        beneficial1DOB: 12181970,
        beneficial1SpendingLimit: "$2,000.00",
        beneficial2FirstName: "",
        beneficial2LastName: "",
        beneficial2MI: "",
        beneficial2ResidentialAddress: "",
        beneficial2City: "",
        beneficial2State: "",
        beneficial2ZipCode: null,
        beneficial2PhoneNumber: null,
        beneficial2SSN: null,
        beneficial2DOB: null,
        beneficial2SpendingLimit: "",
        controllingFirstName: "DANIELLE",
        controllingMI: "A",
        controllingLastName: "BUSCHER",
        controllingResidentialAddress: "2 JULIET LN APT 104",
        controllingCity: "BALTIMORE",
        controllingState: "MD",
        controllingZipCode: 21236,
        controllingSSN: 666535554,
        controllingDOB: "12181970",
        controllingSpendingLimit: "$2,000.00",
        balanceTransfer1Institution: "GTE CREDIT",
        balanceTransfer1Amount: "$3,000.00",
        balanceTransfer1Name: "BROWN",
        balanceTransfer1Address: "PO BOX 2",
        balanceTransfer1ZipCode: "94577",
        balanceTransfer1City: "SAN LEANDRO",
        balanceTransfer1State: "CA",
        balanceTransfer1Account: "1234567890987",
        balanceTransfer2Institution: "",
        balanceTransfer2Amount: "",
        balanceTransfer2Name: "",
        balanceTransfer2Address: "",
        balanceTransfer2ZipCode: "",
        balanceTransfer2City: "",
        balanceTransfer2State: "",
        balanceTransfer2Account: "1234567890987",
        authorized1FirstName: "",
        authorized1MI: "",
        authorized1LastName: "",
        authorized1Suffix: "",
        authorized1DOB: "",
        authorized1SSN: null,
        authorized1SpendingLimit: "",
        authorized2FirstName: "",
        authorized2MI: "",
        authorized2LastName: "",
        authorized2Suffix: "",
        authorized2DOB: "",
        authorized2SSN: null,
        authorized2SpendingLimit: "",
      },
    ],
  };